// Generated by tool/geo/gen_geo.mjs. Do not edit.
const regionShards = <String, String>{
  'ap': 'ap',
  'eu': 'eu',
  'na': 'na',
  'latam': 'na',
  'br': 'na',
  'kr': 'kr',
};
const regionChatAffinities = <String, String>{
  'ap': 'jp1',
  'eu': 'euw1',
  'na': 'na2',
  'latam': 'la1',
  'br': 'br',
  'kr': 'kr1',
};
