import 'dart:convert';
import 'dart:io';

import 'package:path/path.dart' as p;

import 'extract.dart';
import 'project.dart';

typedef Entry = Map<String, Object?>;

/// ARB messages and an explicit symbol-to-key inventory. Expressions requiring
/// structural work stay visible in the manifest, never become fake translations.
class Catalog {
  Catalog(this.arb, this.members, this.messages, this.manual);
  final Map<String, Object?> arb;
  final List<Entry> members;
  final List<Entry> messages;
  final List<Entry> manual;

  static Catalog fromMembers(
    List<Entry> members,
    Map<String, Object?> existing,
  ) {
    final arb = Map<String, Object?>.of(existing);
    final messages = <Entry>[];
    final manual = <Entry>[];
    void add(Entry member, String key, String value, {Object? index}) {
      if (messages.any((e) => e['key'] == key)) {
        throw ProjectException('duplicate ARB key: $key');
      }
      final params = member['params'] as Map<String, String>? ?? {};
      final metadata = <String, Object?>{
        'description':
            member['doc'] ??
            '${member['cls']}.${member['member']} — ${member['section']}',
        if (params.isNotEmpty)
          'placeholders': {
            for (final entry in params.entries)
              entry.key: {'type': entry.value},
          },
        'x-context': member['file'],
      };
      arb[key] = value;
      arb['@$key'] = metadata;
      messages.add({...member, 'key': key, if (index != null) 'index': index});
    }

    for (final member in members) {
      final kind = member['kind'] as String;
      final key = member['key'] as String;
      final value = member['value'];
      if ((kind == 'string' || kind == 'alias') && value is String) {
        add(member, key, value);
      } else if ((kind == 'fn-icu' || kind == 'fn-plural') &&
          member['icu'] is String) {
        final text = member['icu'] as String;
        final params = member['params'] as Map<String, String>;
        if (params.keys.any((p) => !RegExp('\\{$p(?:\\}|,)').hasMatch(text))) {
          manual.add({
            ...member,
            'reason': 'unused argument requires a structural call-site change',
          });
        } else {
          add(member, key, text);
        }
      } else if (kind == 'list' && value is List<Object?>) {
        for (var i = 0; i < value.length; i++) {
          if (value[i] is! String) {
            throw ProjectException('non-string list item: $key/$i');
          }
          add(member, '${key}Item$i', value[i] as String, index: i);
        }
      } else if (kind == 'map' && value is Map<Object?, Object?>) {
        for (final entry in value.entries) {
          final code = entry.key as String;
          final suffix = code.replaceAllMapped(
            RegExp(r'(^|[^a-zA-Z0-9])([a-zA-Z0-9])'),
            (m) => m[2]!.toUpperCase(),
          );
          if (entry.value is! String) {
            throw ProjectException('non-string map item: $key/$code');
          }
          add(member, '$key$suffix', entry.value as String, index: code);
        }
      } else {
        manual.add(member);
      }
    }
    return Catalog(arb, members, messages, manual);
  }

  Map<String, Object?> get manifest => {
    'schema': 1,
    'members': members,
    'messages': messages
        .map(
          (e) => {
            'symbol': '${e['cls']}.${e['member']}',
            'key': e['key'],
            'file': e['file'],
            'kind': e['kind'],
            if (e.containsKey('index')) 'index': e['index'],
            if (e.containsKey('params')) 'params': e['params'],
          },
        )
        .toList(),
    'manual': manual,
  };
}

Future<Catalog> extractCatalog(Project project) async {
  final file = File(p.join(project.root, 'lib/l10n/arb/app_vi.arb'));
  final existing = jsonDecode(file.readAsStringSync()) as Map<String, Object?>;
  final manifest = File(
    p.join(project.root, 'tool/l10n_codemod/manifest.json'),
  );
  if (manifest.existsSync()) {
    final prior =
        jsonDecode(manifest.readAsStringSync()) as Map<String, Object?>;
    for (final message
        in (prior['messages'] as List).cast<Map<String, Object?>>()) {
      existing.remove(message['key']);
      existing.remove('@${message['key']}');
    }
  }
  return Catalog.fromMembers(await extractMembers(project), existing);
}

String encodeJson(Object value) =>
    '${const JsonEncoder.withIndent('  ').convert(value)}\n';

/// Generate direct comparisons against the legacy implementation before
/// rewrites remove it. Include interpolation boundaries and plural branches.
String paritySource(Catalog catalog) {
  final imports =
      catalog.messages.map((e) => e['file'] as String).toSet().toList()..sort();
  final b = StringBuffer('// Generated by l10n parity. Do not hand edit.\n')
    ..writeln("import 'package:flutter/widgets.dart' show Locale;")
    ..writeln("import 'package:flutter_test/flutter_test.dart';")
    ..writeln("import 'package:valvn/core/l10n/l10n.dart';");
  for (final file in imports) {
    b.writeln("import 'package:valvn/${file.substring(4)}';");
  }
  b.writeln(
    "void main() { final l10n = lookupAppLocalizations(const Locale('vi'));",
  );
  for (final entry in catalog.messages) {
    final symbol = '${entry['cls']}.${entry['member']}';
    final key = entry['key'] as String;
    final params = entry['params'] as Map<String, String>? ?? {};
    var cases = <List<Object>>[[]];
    for (final param in params.entries) {
      final values = param.value == 'int'
          ? <Object>[0, 1, 2, 5, 99]
          : <Object>['', 'Nguyễn Văn A', '{value}\n!'];
      cases = [
        for (final prior in cases)
          for (final value in values) [...prior, value],
      ];
    }
    b.writeln('test(${dartLiteral(key)}, () {');
    for (final args in cases) {
      final values = args.map(dartLiteral).join(', ');
      var legacy = params.isEmpty ? symbol : '$symbol($values)';
      if (entry['index'] != null) {
        legacy = '$symbol[${dartLiteral(entry['index']!)}]';
      }
      final generated = params.isEmpty ? 'l10n.$key' : 'l10n.$key($values)';
      b.writeln('expect($generated, $legacy);');
    }
    b.writeln('});');
  }
  b.writeln('}');
  return b.toString();
}

String dartLiteral(Object value) {
  if (value is! String) {
    return '$value';
  }
  final escaped = value
      .replaceAll(r'\', r'\\')
      .replaceAll("'", r"\'")
      .replaceAll(r'$', r'\$')
      .replaceAll('\n', r'\n')
      .replaceAll('\r', r'\r')
      .replaceAll('\t', r'\t');
  return "'$escaped'";
}

/// Use the running SDK's formatter, keeping generated parity byte-identical
/// to CI's `dart format`. A temporary single file is always removed.
String formatDartSource(Project project, String source) {
  final file = File(p.join(project.reportsDir, '.parity-format.dart'));
  file.parent.createSync(recursive: true);
  try {
    file.writeAsStringSync(source);
    final result = Process.runSync(
      Platform.resolvedExecutable,
      ['format', '--output=show', '--summary=none', file.path],
      stdoutEncoding: utf8,
      stderrEncoding: utf8,
    );
    final output = result.stdout as String;
    if (result.exitCode != 0 || !output.startsWith('// Generated')) {
      throw ProjectException('Dart formatter failed: ${result.stderr}');
    }
    return output.replaceAll('\r\n', '\n');
  } finally {
    if (file.existsSync()) file.deleteSync();
  }
}

bool writeOrCheck(String path, String value, {required bool check}) {
  final file = File(path);
  if (file.existsSync() &&
      file.readAsStringSync().replaceAll('\r\n', '\n') == value) {
    return true;
  }
  if (check) {
    stderr.writeln('out of date: $path');
    return false;
  }
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(value);
  return true;
}
