import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { resolve, dirname } from 'node:path';

// Pinned upstream data: regeneration never silently changes the CLDR release.
const root = resolve(dirname(fileURLToPath(import.meta.url)), '../..');
const version = '48.0.0';
const base = `https://raw.githubusercontent.com/unicode-org/cldr-json/${version}/cldr-json`;
async function get(path) {
  if (process.argv.includes('--offline')) {
    if (path.includes('codeMappings')) {
      const data = JSON.parse(await readFile(resolve(root, 'assets/data/countries.json'), 'utf8'));
      return {supplemental:{codeMappings:Object.fromEntries(Object.entries(data.countries).map(([c,v])=>[c,{_alpha3:v.a3,_numeric:v.m49}]))}};
    }
    const [, locale, type] = path.match(/main\/([^/]+)\/(territories|languages)\.json/);
    const data = JSON.parse(await readFile(resolve(root, `assets/l10n/${type === 'territories' ? 'countries' : 'languages'}/${locale}.json`), 'utf8'));
    if (data.cldr !== version) throw new Error('Offline CLDR release mismatch');
    const names = { ...data.names };
    if (type === 'territories') {
      for (const [code, aliases] of Object.entries(data.aliases ?? {})) {
        aliases.forEach((alias, i) => { names[`${code}-alt-cached-${i}`] = alias; });
      }
    }
    return {main:{[locale]:{localeDisplayNames:{[type]:names}}}};
  }
  const r = await fetch(`${base}/${path}`, { signal: AbortSignal.timeout(15000) });
  if (!r.ok) throw new Error(`CLDR ${path}: ${r.status}`);
  return r.json();
}
async function save(path, data) {
  const file = resolve(root, path);
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, `${JSON.stringify(data, null, 2)}\n`);
}
const mappings = (await get('cldr-core/supplemental/codeMappings.json')).supplemental.codeMappings;
const source = await readFile(resolve(root, 'server/community/src/geo/countries.ts'), 'utf8');
const iso = [...source.matchAll(/^  ([a-z]{3}): '([A-Z]{2})'/gm)].map(m => m[2]).sort();
if (new Set(iso).size !== 249) throw new Error('ISO source must contain exactly 249 codes');
const codes = [...iso, 'XK'].sort();
const regions = {
  ap: { shard: 'ap', feed: 'ap', chat: 'jp1', order: 1 },
  eu: { shard: 'eu', feed: 'eu', chat: 'euw1', order: 2 },
  na: { shard: 'na', feed: 'na', chat: 'na2', order: 3 },
  latam: { shard: 'na', feed: 'latam', chat: 'la1', order: 4 },
  br: { shard: 'na', feed: 'br', chat: 'br', order: 5 },
  kr: { shard: 'kr', feed: 'kr', chat: 'kr1', order: 6 },
};
await save('assets/data/regions.json', { schema: 1, dataVersion: 1, regions });
await mkdir(resolve(root, 'lib/core/geo'), { recursive: true });
// One generated table serves synchronous auth/host code and the asset loader.
await writeFile(resolve(root, 'lib/core/geo/region_data.g.dart'),
  `// Generated by tool/geo/gen_geo.mjs. Do not edit.\nconst regionShards = <String, String>{\n${Object.entries(regions).map(([r,v])=>`  '${r}': '${v.shard}',`).join('\n')}\n};\nconst regionChatAffinities = <String, String>{\n${Object.entries(regions).map(([r,v])=>`  '${r}': '${v.chat}',`).join('\n')}\n};\n`);
// Country coverage and language names are authoritative CLDR data. Region hints
// are deliberately conservative and never determine network routing.
const hints = {
  ap: 'VN BN KH HK ID LA MO MY MM PH SG TW TH TL JP IN LK BD NP BT MV AU NZ',
  na: 'US CA', br: 'BR', kr: 'KR',
  latam: 'MX GT BZ HN SV NI CR PA CU HT DO JM CO VE EC AR BO CL PY PE UY',
  eu: 'ZA LB JO EG IQ PS SA BH QA KW OM AE LY DZ MA TN',
};
const countries = Object.fromEntries(codes.map(code => {
  const map = mappings[code];
  if (!map?._alpha3 || !map?._numeric) throw new Error(`Missing mapping: ${code}`);
  const region = Object.entries(hints).find(([, list]) => list.split(' ').includes(code))?.[0] ?? null;
  // Hints are not an availability claim. Preserve unknown unless the audit
  // explicitly names the country; no blanket regional guesses or embargo list.
  return [code, { a3: map._alpha3, m49: map._numeric, region,
    conf: region ? 'unverified' : 'none', status: 'unknown',
    console: null, notes: [], src: [], ...(code === 'XK' ? { nonIso: true } : {}) }];
}));
const sources = {
  'riot-gift': { url: 'https://support.riotgames.com/en-us/valorant/store/gifting-in-valorant', kind: 'official', checked: '2026-10-01' },
  'riot-sea': { url: 'https://support.riotgames.com/en-us/valorant/billing/methods-of-payment-for-valorant-southeast-asia', kind: 'official', checked: '2026-10-01' },
  'riot-console': { url: 'https://support.riotgames.com/en-us/valorant/gameplay/valorant-console-guide', kind: 'official', checked: '2026-10-01' },
  'riot-capetown': { url: 'https://playvalorant.com/en-us/news/dev/valorant-s-cape-town-servers-are-live/', kind: 'official', checked: '2026-10-01' },
};
for (const code of 'VN BN KH HK ID LA MO MY MM PH SG TW TH TL'.split(' ')) {
  Object.assign(countries[code], { region: 'ap', status: 'available', conf: 'region', via: 'area:riot-sea', src: ['riot-sea', 'riot-gift'] });
}
for (const [code, region] of Object.entries({US:'na', CA:'na', BR:'br', KR:'kr', TR:'eu', RU:'eu', UA:'eu', EG:'eu'})) {
  Object.assign(countries[code], {region, status:'available', conf:'region', via:'area:riot-gift', src:['riot-gift']});
}
for (const code of ['JP', 'AU', 'NZ']) Object.assign(countries[code],
  { status: 'available', conf:'region', via:'area:riot-console', console:true, src:['riot-console'] });
for (const code of ['US','CA','BR']) { countries[code].console = true; countries[code].src.push('riot-console'); }
Object.assign(countries.ZA, { status:'available', conf:'official', via:'named', src:['riot-capetown'] });
countries.AQ.status = 'na';
await save('assets/data/countries.json', { schema: 1, dataVersion: 1, cldr: version, countries, sources });
await writeFile(resolve(root, 'lib/core/geo/country_data.g.dart'), `// Generated by tool/geo/gen_geo.mjs. Do not edit.\nconst countryAlpha3To2 = <String, String>{\n${Object.entries(countries).map(([c,v])=>`  '${v.a3.toLowerCase()}': '${c}',`).join('\n')}\n};\n`);
const locales = ['ar','de','en','es','es-MX','fr','id','it','ja','ko','pl','pt','ru','th','tr','vi','zh','zh-Hant'];
for (const locale of locales) {
  const raw = await get(`cldr-localenames-full/main/${locale}/territories.json`);
  const territories = raw.main[locale].localeDisplayNames.territories;
  const names = Object.fromEntries(codes.map(code => {
    const name = territories[`${code}-alt-short`] ?? territories[code];
    if (!name) throw new Error(`Missing ${locale} country: ${code}`);
    return [code, name];
  }));
  const collator = new Intl.Collator(locale);
  const order = [...codes].sort((a, b) => collator.compare(names[a], names[b]) || a.localeCompare(b));
  const aliases = Object.fromEntries(codes.flatMap(code => {
    const alternatives = [...new Set(Object.entries(territories)
      .filter(([key]) => key === code || key.startsWith(`${code}-alt-`))
      .map(([, value]) => value).filter(value => value !== names[code]))];
    return alternatives.length ? [[code, alternatives]] : [];
  }));
  await save(`assets/l10n/countries/${locale}.json`, { cldr: version, locale, order, names, aliases });
  const langs = (await get(`cldr-localenames-full/main/${locale}/languages.json`)).main[locale].localeDisplayNames.languages;
  await save(`assets/l10n/languages/${locale}.json`, { cldr: version, locale, names: langs });
}
if (!process.argv.includes('--offline')) {
  const license = await fetch(`https://raw.githubusercontent.com/unicode-org/cldr-json/${version}/LICENSE`, {signal: AbortSignal.timeout(15000)});
  if (!license.ok) throw new Error('Missing Unicode license');
  await writeFile(resolve(root, 'assets/l10n/UNICODE-LICENSE.txt'), await license.text());
}
console.log(`Generated ${codes.length} countries in ${locales.length} locales; CLDR ${version}.`);
