'use client';

import { useEffect, useRef, useState } from 'react';
import { Bell, Check, ChevronRight, CircleHelp, Gem, Home, Layers3, MessageCircle, Moon, Search, Settings2, Shield, SlidersHorizontal, Sparkles, Store, Sun, UserRound, Users, X } from 'lucide-react';
import { HomeDashboard, RankCard, SectionTitle } from './dashboard';

const tabs = [{ label: 'Trang chủ', icon: Home }, { label: 'Cửa hàng', icon: Store }, { label: 'Cộng đồng', icon: MessageCircle }, { label: 'Bộ sưu tập', icon: Layers3 }, { label: 'Hồ sơ', icon: UserRound }];
const skins = [{ name: 'Reaver', weapon: 'Vandal', color: 'purple', rarity: 'Cao cấp' }, { name: 'Prime', weapon: 'Phantom', color: 'gold', rarity: 'Cao cấp' }, { name: 'Oni', weapon: 'Phantom', color: 'green', rarity: 'Cao cấp' }, { name: 'Ion', weapon: 'Operator', color: 'blue', rarity: 'Cao cấp' }];

export function MobilePreview() {
  const [tab, setTab] = useState(0);
  const [dark, setDark] = useState(false);
  const [sheet, setSheet] = useState<string | null>(null);
  const [filter, setFilter] = useState('Tất cả');
  const [search, setSearch] = useState('');
  const [saved, setSaved] = useState<string[]>([]);
  const [notifications, setNotifications] = useState(true);
  const dialog = useRef<HTMLDialogElement>(null);
  useEffect(() => { if (sheet) dialog.current?.showModal(); else dialog.current?.close(); }, [sheet]);
  function navigate(index: number) { setTab(index); setFilter('Tất cả'); setSearch(''); window.scrollTo({ top: 0 }); }
  function close() { setSheet(null); }
  const isSettings = sheet === 'Cài đặt';
  return <div className={`preview ${dark ? 'dark' : ''}`}>
    <div className="app-shell">
      <div className="demo-banner"><span><i /> BẢN XEM TRƯỚC MOBILE</span><span>Dữ liệu minh họa</span></div>
      <header className="app-header"><div><span className="brand">VAL<span>VN</span><i /></span><h1>{tabs[tab].label}</h1></div><div className="header-actions"><button className="round-button notification" aria-label="Thông báo" onClick={() => setSheet('Thông báo')}><Bell size={19} /><i /></button><button className="avatar" aria-label="Mở hồ sơ minh họa" onClick={() => navigate(4)}>V</button></div></header>
      <main key={tab}>
        {tab === 0 && <HomeDashboard navigate={navigate} details={setSheet} />}
        {tab === 1 && <><div className="intro"><p>Một chút cá tính cho mỗi trận đấu.</p></div><div className="wallet"><span><Gem size={15} /> 2.450 <small>VP</small></span><span><Sparkles size={15} /> 120 <small>RP</small></span><span className="subtle">Ví minh họa</span></div><div className="feature-banner"><img src="/images/tactical-city.png" alt="Khung cảnh thành phố gaming" /><div><span>BỘ SƯU TẬP NỔI BẬT</span><h2>Dấu ấn của bạn.</h2><p>Khám phá diện mạo mới</p></div></div><SectionTitle>Ưu đãi hằng ngày</SectionTitle><p className="subtle store-note">Mẫu thẻ thiết kế · Không phải cửa hàng trực tiếp</p><div className="skin-grid">{skins.map(skin => <button className={`card skin-card ${skin.color}`} key={skin.name} onClick={() => setSheet(`${skin.name} ${skin.weapon}`)}><div className="skin-art"><Gem size={45} strokeWidth={1} /><span>{skin.weapon.toUpperCase()}</span></div><div className="skin-content"><span className="skin-rarity">◇ {skin.rarity}</span><h3>{skin.name} {skin.weapon}</h3><p>1.775 <small>VP · Minh họa</small></p></div></button>)}</div></>}
        {tab === 2 && <><div className="intro"><p>Đồng đội tốt. Trận đấu hay.</p></div><div className="search"><Search size={18} /><input aria-label="Tìm bài đăng" placeholder="Tìm đồng đội, bài viết…" value={search} onChange={e => setSearch(e.target.value)} /><SlidersHorizontal size={17} /></div><div className="segments">{['Tất cả', 'Tìm đội', 'Thảo luận'].map(item => <button aria-pressed={filter === item} className={filter === item ? 'selected' : ''} key={item} onClick={() => setFilter(item)}>{item}</button>)}</div><SectionTitle>Góc cộng đồng</SectionTitle>{[{ id: 'Minh', rank: 'Kim cương', tag: 'Tìm đội', title: 'Tìm duo leo rank buổi tối', text: 'Mình chơi Controller, tìm đồng đội chill có mic. Cùng nhau lên Bất tử nhé!', time: '12 phút trước' }, { id: 'Linh', rank: 'Bạch kim', tag: 'Thảo luận', title: 'Đặc vụ yêu thích của bạn là ai?', text: 'Chia sẻ lựa chọn và những mẹo nhỏ của bạn với mọi người.', time: '35 phút trước' }].filter(post => (filter === 'Tất cả' || post.tag === filter) && `${post.title} ${post.text}`.toLocaleLowerCase('vi').includes(search.toLocaleLowerCase('vi'))).map(post => <article className="card post" key={post.id}><div className="post-author"><span className="avatar small">{post.id[0]}</span><div><h3>{post.id} <span>#{post.rank}</span></h3><p>{post.time}</p></div><span className="post-tag">{post.tag}</span></div><h3>{post.title}</h3><p>{post.text}</p><div className="post-actions"><button aria-pressed={saved.includes(post.id)} onClick={() => setSaved(saved.includes(post.id) ? saved.filter(id => id !== post.id) : [...saved, post.id])}>{saved.includes(post.id) ? <Check size={15} /> : <Gem size={15} />}{saved.includes(post.id) ? 'Đã lưu' : 'Lưu bài'}</button><button onClick={() => setSheet(post.title)}><MessageCircle size={15} /> Xem thảo luận</button></div></article>)}<div className="card community-note"><Users size={25} /><h3>Chơi tốt hơn cùng nhau</h3><p>Các bài đăng ở đây là nội dung mẫu để xem thử bố cục.</p></div></>}
        {tab === 3 && <><div className="intro"><p>Mọi dấu ấn. Một bộ sưu tập.</p></div><div className="collection-cover"><span className="eyebrow">THẺ NGƯỜI CHƠI</span><Shield size={56} strokeWidth={1} /><h2>Ready for the next round.</h2><span>VALVN #DEMO</span></div><SectionTitle>Trang bị hiện tại</SectionTitle><div className="card list">{[['Vandal', 'Reaver'], ['Phantom', 'Oni'], ['Danh hiệu', 'Không ngừng tiến lên']].map(([label, value]) => <button key={label} onClick={() => setSheet(`${label} · ${value}`)}><span className="icon-tile violet"><Gem size={18} /></span><div><h3>{label}</h3><p>{value}</p></div><ChevronRight size={17} /></button>)}</div><SectionTitle>Duyệt bộ sưu tập</SectionTitle><div className="category-grid">{['Súng trường', 'Súng ngắn', 'Cận chiến', 'Phụ kiện'].map((item, index) => <button className="card category" key={item} onClick={() => setSheet(item)}><Gem size={23} /><h3>{item}</h3><p>{[24, 12, 8, 36][index]} vật phẩm mẫu</p><ChevronRight size={14} /></button>)}</div></>}
        {tab === 4 && <><section className="card profile"><span className="profile-avatar">V</span><h2>ValVN <span>#DEMO</span></h2><p>AP · Việt Nam</p><span className="demo-chip">Tài khoản minh họa</span></section><RankCard /><SectionTitle>Tổng quan mùa</SectionTitle><div className="stats"><div className="card"><b>58%</b><span>Tỉ lệ thắng</span></div><div className="card"><b>1,24</b><span>K/D trung bình</span></div><div className="card"><b>42</b><span>Trận đã chơi</span></div></div><SectionTitle>Tuỳ chọn</SectionTitle><div className="card list">{[{ name: 'Cài đặt', icon: Settings2 }, { name: 'Về bản xem trước', icon: CircleHelp }].map(item => <button key={item.name} onClick={() => setSheet(item.name)}><span className="icon-tile neutral"><item.icon size={20} /></span><h3>{item.name}</h3><ChevronRight size={17} /></button>)}<button onClick={() => setDark(!dark)}><span className="icon-tile neutral">{dark ? <Sun size={20} /> : <Moon size={20} />}</span><h3>{dark ? 'Chuyển giao diện sáng' : 'Chuyển giao diện tối'}</h3><ChevronRight size={17} /></button></div></>}
      </main>
      <nav className="bottom-nav" aria-label="Điều hướng chính">{tabs.map((item, index) => <button aria-current={tab === index ? 'page' : undefined} className={tab === index ? 'active' : ''} key={item.label} onClick={() => navigate(index)}><span><item.icon size={21} strokeWidth={tab === index ? 2.3 : 1.8} /></span><small>{item.label}</small></button>)}</nav>
      <dialog ref={dialog} onCancel={close} onClose={close} onClick={e => { if (e.target === e.currentTarget) close(); }}><div className="sheet-handle" /><div className="sheet-heading"><h2>{sheet}</h2><button aria-label="Đóng" className="round-button" onClick={close}><X size={20} /></button></div>{isSettings ? <><p className="sheet-description">Tuỳ chỉnh bản xem trước trên thiết bị của bạn.</p><button className="setting-row" onClick={() => setDark(!dark)}><span>Giao diện tối</span><span role="switch" aria-checked={dark} className={`toggle ${dark ? 'on' : ''}`}><i /></span></button><button className="setting-row" onClick={() => setNotifications(!notifications)}><span>Thông báo minh họa</span><span role="switch" aria-checked={notifications} className={`toggle ${notifications ? 'on' : ''}`}><i /></span></button></> : <><span className="icon-tile coral sheet-icon">{sheet === 'Thông báo' ? <Bell size={24} /> : <Sparkles size={24} />}</span><p className="sheet-description">{sheet === 'Thông báo' ? 'Bạn đã cập nhật tất cả! Chưa có thông báo mới trong bản demo.' : sheet === 'Trận gần nhất' ? 'Ascent · Chiến thắng 13–8 · K/D/A: 22 / 14 / 6 · +18 RR. Đây là dữ liệu minh họa, không phải lịch sử Riot thật.' : sheet === 'Battle Pass' ? 'Tiến độ minh họa: cấp 38/50. Còn 12 cấp để hoàn thành mùa.' : 'Đây là bản demo thiết kế tương tác của ValVN. Nội dung minh họa, chưa kết nối tài khoản Riot, không mua hàng hoặc lưu dữ liệu thật.'}</p><button className="primary-button" onClick={close}>Đã hiểu <Check size={17} /></button></>}</dialog>
    </div>
    <aside className="desktop-caption"><span className="brand">VAL<span>VN</span></span><h2>Đồng hành.<br />Mỗi trận đấu.</h2><p>Bản xem trước giao diện app mobile.<br />Thử 5 tab và chuyển sáng / tối trong Hồ sơ.</p><span>THIẾT KẾ MOBILE · DỮ LIỆU MINH HỌA</span></aside>
  </div>;
}
