"""Generates lib/core/util/search_fold_table.dart.

Dart has no Unicode normalisation in its core libraries, so the
"NFD + strip combining marks" step of `foldForSearch` uses a table of every
precomposed Latin / Greek / Cyrillic / Arabic letter whose canonical
decomposition contains combining marks, mapped to its lowercase base letters
(plus a few letters that do not decompose but are searched as ASCII:
đ → d, ß → ss, æ → ae, œ → oe, ø → o, ł → l, ı → i, ð → d, ς → σ).

Japanese kana, Hangul and CJK are deliberately left out (they are not folded).

Run: python tool/gen_search_fold_table.py
"""

import unicodedata
from pathlib import Path

RANGES = [
    (0x00C0, 0x024F),  # Latin-1 Supplement letters, Latin Extended-A/B
    (0x1E00, 0x1EFF),  # Latin Extended Additional (Vietnamese…)
    (0x0370, 0x03FF),  # Greek
    (0x1F00, 0x1FFF),  # Greek Extended
    (0x0400, 0x04FF),  # Cyrillic
    (0x0620, 0x06FF),  # Arabic letters with hamza / madda
]

SPECIAL = {
    'đ': 'd', 'Đ': 'd', 'ð': 'd', 'Ð': 'd',
    'ß': 'ss', 'ẞ': 'ss',
    'æ': 'ae', 'Æ': 'ae',
    'œ': 'oe', 'Œ': 'oe',
    'ø': 'o', 'Ø': 'o',
    'ł': 'l', 'Ł': 'l',
    'ı': 'i', 'İ': 'i',
    'ς': 'σ',
}


def fold(ch: str) -> str:
    if ch in SPECIAL:
        return SPECIAL[ch]
    nfd = unicodedata.normalize('NFD', ch)
    base = ''.join(c for c in nfd if not unicodedata.combining(c)
                   and unicodedata.category(c) not in ('Mn', 'Me'))
    base = base.lower()
    return ''.join(SPECIAL.get(c, c) for c in base)


def main() -> None:
    table = {}
    for lo, hi in RANGES:
        for cp in range(lo, hi + 1):
            ch = chr(cp)
            if unicodedata.category(ch)[0] != 'L':
                continue
            folded = fold(ch)
            if folded and folded != ch:
                table[cp] = folded
    for ch, folded in SPECIAL.items():
        table[ord(ch)] = folded

    lines = [
        '// GENERATED by tool/gen_search_fold_table.py from Unicode '
        f'{unicodedata.unidata_version} — do not edit by hand.',
        '//',
        '// Precomposed letter → lowercase base letters (canonical decomposition',
        '// without combining marks, plus đ/ß/æ/œ/ø/ł/ı/ð/ς). Used by',
        '// `foldForSearch` (search_text.dart).',
        '',
        '/// Code point → folded replacement.',
        'const Map<int, String> kSearchFoldTable = {',
    ]
    for cp in sorted(table):
        rep = table[cp].replace('\\', '\\\\').replace("'", "\\'")
        lines.append(f"  0x{cp:04X}: '{rep}', // {chr(cp)}")
    lines.append('};')
    out = Path(__file__).resolve().parent.parent / 'lib' / 'core' / 'util' / 'search_fold_table.dart'
    out.write_text('\n'.join(lines) + '\n', encoding='utf-8')
    print(f'{len(table)} entries -> {out}')


if __name__ == '__main__':
    main()
